<Project Sdk="Godot.NET.Sdk/4.1.1">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>CropsandCorpses</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="scripts\ui\crafting\" />
    <Folder Include="scripts\ui\inventory\" />
    <Folder Include="scripts\ui\overlay\" />
  </ItemGroup>
</Project>